### ISSUE TITLE
你好.最新x86固件openclash不会自启动

### ISSUE THREAD

**Issue by Genion** [violarulan/openwrt#1]
用的一键配置,重启路由不会自启动openclash.  守护程序:未运行.

**Comment by violarulan** [comment]
居然有人用这里的！😂

@Genion 最新的我不清楚，我目前使用的是这个 https://github.com/violarulan/openwrt/releases/tag/2022.01.07-1900 是正常的

**Comment by Genion** [comment]
> 

感谢分享，终于解决了问题。之前试了好多固件都不行。
